image: curlimages/curl:latest

stages:
  - publish

update-packagist:
  stage: publish
  script:
    - >
      curl -XPOST -H 'content-type:application/json' 
      "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" 
      -d "{\"repository\":{\"url\":\"https://gitlab.com/${CI_PROJECT_PATH}\"}}"
  rules:
    - if: $CI_COMMIT_TAG
